# <center>Machine Learning Project</center>

** **
## <center>*03.5 - Random Forest*</center>

** **

Description of the notebook

Simple Model with evaluation


The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Louren√ßo - 2021639


## <span style="color:salmon"> Table of Contents </span>

<a class="anchor" id="top"></a>

1. [Importing Libraries & Data](#one-bullet) 

2. [Prepare Dataset](#two-bullet)

   2.1 [Separate Target](#two-one-bullet) 

   2.2 [Train Validation Split](#two-two-bullet)
   
   2.3 [Impute Missing Values](#two-three-bullet) 
   
   2.4 [Scaling Data](#two-four-bullet) <br><br>

3. [Model Training](#three-bullet)

4. [Model Evaluation](#four-bullet) 

   4.1 [Training Evaluation](#four-one-bullet) 
   
   4.2 [Validation Evaluation](#four-two-bullet) <br><br>

5. [Test Prediction](#five-bullet)

<a class="anchor" id="one-bullet"> 
    
# <span style="color:salmon"> 1. Importing Libraries & Data </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [2]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from catboost import CatBoostClassifier

from utils import *

In [3]:
# Import  for training and validation
df = pd.read_csv('./preprocessed_data/train_data.csv', index_col = 'Claim Identifier')
df

,Accident Date,Age at Injury,Average Weekly Wage,Birth Year,IME-4 Count,Number of Dependents,Known Accident Date,Known Assembly Date,Known C-2 Date,Known C-3 Date,...,Zip_Code_Hash_13,Zip_Code_Hash_14,Zip_Code_Hash_15,Zip_Code_Hash_16,Zip_Code_Hash_17,Zip_Code_Hash_18,Zip_Code_Hash_19,Claim Injury Type Encoded,Accident_Season_Sin,Accident_Season_Cos
Claim Identifier,,,,,,,,,,,,,,,,,,,,,
5393875,2019-12-30,31.0,NaN,1988.0,0.0,1.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.000000e+00,1.000000e+00
5393091,2019-08-30,46.0,1745.93,1973.0,4.0,4.0,1,1,1,1,...,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3,1.224647e-16,-1.000000e+00
5393889,2019-12-06,40.0,1434.80,1979.0,0.0,6.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,3,-1.000000e+00,-1.836970e-16
5393887,2019-12-30,61.0,NaN,1958.0,0.0,1.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.000000e+00,1.000000e+00
5393863,2019-12-26,67.0,NaN,1952.0,0.0,5.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.000000e+00,1.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6165265,2022-12-14,35.0,NaN,1987.0,0.0,4.0,1,1,1,0,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165285,2022-12-15,33.0,NaN,1989.0,0.0,6.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165506,2022-12-13,61.0,991.08,1961.0,1.0,3.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,3,-1.000000e+00,-1.836970e-16
6165339,2022-12-14,24.0,NaN,1998.0,0.0,5.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165075,2022-12-13,72.0,NaN,1950.0,0.0,3.0,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16

In [4]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

,Accident Date,Age at Injury,Average Weekly Wage,Birth Year,IME-4 Count,Number of Dependents,Known Accident Date,Known Assembly Date,Known C-2 Date,Known C-3 Date,...,Zip_Code_Hash_12,Zip_Code_Hash_13,Zip_Code_Hash_14,Zip_Code_Hash_15,Zip_Code_Hash_16,Zip_Code_Hash_17,Zip_Code_Hash_18,Zip_Code_Hash_19,Accident_Season_Sin,Accident_Season_Cos
Claim Identifier,,,,,,,,,,,,,,,,,,,,,
6165911,2022-12-24,19.0,NaN,2003.0,0.0,1,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166141,2022-11-20,19.0,NaN,2003.0,0.0,1,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000e+00,-1.836970e-16
6165907,2022-12-26,59.0,NaN,1963.0,0.0,0,1,1,1,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166047,2022-12-28,55.0,NaN,1967.0,0.0,6,1,1,1,0,...,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166102,2022-12-20,25.0,NaN,1997.0,0.0,5,1,1,1,0,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-1.000000e+00,-1.836970e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6553137,2012-09-12,52.0,NaN,1960.0,0.0,5,1,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.224647e-16,-1.000000e+00
6553119,2024-05-22,59.0,NaN,1965.0,0.0,1,1,1,0,1,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17
6553542,2024-05-06,45.0,NaN,1979.0,0.0,5,1,1,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17
6553455,2024-02-24,42.0,NaN,1981.0,0.0,5,1,1,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6553594,2024-06-05,NaN,NaN,NaN,0.0,5,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17

<a class="anchor" id="two-bullet"> 
    
# <span style="color:salmon"> 2. Prepare Dataset </span> 
</a>    
</div>
<a href="#top">Top &#129033;</a>

<a class="anchor" id="two-one-bullet"> 
    
## <span style="color:salmon"> 2.1 Separate Target </span> 
</a>    
</div>

In [5]:
# Define features and target
X = df.drop('Claim Injury Type Encoded', axis=1)
y = df['Claim Injury Type Encoded']

<a class="anchor" id="two-twpo-bullet"> 
    
## <span style="color:salmon"> 2.2 Train Validation Split </span> 
</a>    
</div>

In [6]:
# Split the data into training and testing sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [7]:
X_test = test_df.copy()

<a class="anchor" id="two-three-bullet"> 
    
## <span style="color:salmon"> 2.3 Impute Missing Values </span> 
</a>    
</div>

*Check missing values in each dataset*

In [8]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year               1726
Age at Injury            1726
Average Weekly Wage    291126
dtype: int64

In [9]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year               460
Age at Injury            460
Average Weekly Wage    72973
dtype: int64

In [10]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                982
Age at Injury             982
Average Weekly Wage    335753
dtype: int64

*Input `Average Weekly Wage` and variables created from it*

In [11]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [12]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [13]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [14]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

*Drop Dates*

In [15]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

*Define columns to use in model training*

In [16]:
# Get feature names as a string (separated by commas)
features = ', '.join(X_train.columns)

<a class="anchor" id="two-four-bullet"> 
    
## <span style="color:salmon"> 2.4 Scaling Data </span> 
</a>    
</div>

In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

<a class="anchor" id="three-bullet"> 
    
# <span style="color:salmon"> 3. Model Training </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [18]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

In [19]:
config = {'iterations': 500, 'learning_rate': 0.1557532043305807, 'depth': 6, 'l2_leaf_reg': 9.91550442068039}
model = CatBoostClassifier(
        iterations=config["iterations"],
        learning_rate=config["learning_rate"],
        depth=config["depth"],
        l2_leaf_reg=config["l2_leaf_reg"],
        loss_function="MultiClass", 
        eval_metric="MultiClass",  
        custom_metric=['F1'], 
        verbose=0
    )
model.fit(X_train, y_train)

<a class="anchor" id="four-bullet"> 
    
# <span style="color:salmon"> 4. Model Evaluation </span> 
</a>    
</div>
<a href="#top">Top &#129033;</a>

<a class="anchor" id="four-one-bullet"> 
    
## <span style="color:salmon"> 4.1 Training Evaluation </span> 
</a>    
</div>

In [20]:
# Make training predictions
y_train_pred = model.predict(X_train)

In [21]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))

Confusion Matrix:
[[  3864   5742    181    181     11      0      0      1]
 [  1563 228448   1127   1619    101      0      0      4]
 [    53  29225   4979  18830   2033      0      0      5]
 [    51   6538   1899 104439   5842      7      0     29]
 [     0    566    629  16584  20842      3      0      0]
 [     0      9     45   2834    458     23      0      0]
 [     0      0      0     72      6      0      0      0]
 [     2     62     10    140      1      0      0    161]]

Classification Report:

c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                 precision    recall  f1-score   support

   1. CANCELLED       0.70      0.39      0.50      9980
    2. NON-COMP       0.84      0.98      0.91    232862
    3. MED ONLY       0.56      0.09      0.16     55125
   4. TEMPORARY       0.72      0.88      0.79    118805
5. PPD SCH LOSS       0.71      0.54      0.61     38624
     6. PPD NSL       0.70      0.01      0.01      3369
         7. PTD       0.00      0.00      0.00        78
       8. DEATH       0.81      0.43      0.56       376

       accuracy                           0.79    459219
      macro avg       0.63      0.41      0.44    459219
   weighted avg       0.76      0.79      0.75    459219

c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

<a class="anchor" id="four-two-bullet"> 
    
## <span style="color:salmon"> 4.2 Validation Evaluation </span> 
</a>    
</div>

In [22]:
# Make validation predictions
y_val_pred = model.predict(X_val)

In [23]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))

Confusion Matrix:
[[  976  1417    40    62     0     0     0     0]
 [  443 57037   315   388    31     0     0     2]
 [   16  7399  1078  4774   513     0     0     1]
 [   17  1723   490 26007  1458     0     0     7]
 [    0   166   155  4263  5072     0     0     0]
 [    0     0    11   702   127     2     0     0]
 [    0     0     1    14     3     0     0     1]
 [    0    23     6    38     0     0     0    27]]

Classification Report:

c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                 precision    recall  f1-score   support

   1. CANCELLED       0.67      0.39      0.49      2495
    2. NON-COMP       0.84      0.98      0.91     58216
    3. MED ONLY       0.51      0.08      0.14     13781
   4. TEMPORARY       0.72      0.88      0.79     29702
5. PPD SCH LOSS       0.70      0.53      0.60      9656
     6. PPD NSL       1.00      0.00      0.00       842
         7. PTD       0.00      0.00      0.00        19
       8. DEATH       0.71      0.29      0.41        94

       accuracy                           0.79    114805
      macro avg       0.65      0.39      0.42    114805
   weighted avg       0.76      0.79      0.74    114805

c:\Users\abdar\anaconda3\envs\ML_Project\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

<a class="anchor" id="five-bullet"> 
    
# <span style="color:salmon"> 5. Test Predictions </span> 
</a>    
</div>

<a href="#top">Top &#129033;</a>

In [ ]:
# Make validation predictions
y_test_pred = model.predict(X_test)
y_test_pred = y_test_pred.ravel()

In [28]:
y_test_final = np.array([class_mapping[i] for i in y_test_pred])

In [29]:
test_id = test_df.index

In [30]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_final
})

In [31]:
# Save the DataFrame to a CSV file
submission_df.to_csv('./submissions/Group49_Version05.csv', index=False)

In [32]:
# save_results_csv(model, features, y_train, y_train_pred, y_val, y_val_pred)