# <center>Machine Learning Project</center>

** **
## <center>*03.7 - Neural Networks*</center>

** **

The members of the `team` are:
- Ana Farinha - 20211514
- Francisco Capontes - 20211692
- Sofia Gomes - 20240848
- Rui Louren√ßo - 2021639

In [ ]:
# Import libraries
import pandas as pd
import numpy as np

#make the split here
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import StratifiedKFold
import time


from utils import *

## <span style="color:salmon"> 1. Import Dataset </span>

In [ ]:
# Import dataset
df = pd.read_csv('preprocessed_data/train_data.csv', index_col="Claim Identifier")
df

,Accident Date,Age at Injury,Average Weekly Wage,Birth Year,IME-4 Count,WCIO Cause of Injury Code,WCIO Nature of Injury Code,WCIO Part Of Body Code,Number of Dependents,Known Accident Date,...,Zip_Code_Hash_13,Zip_Code_Hash_14,Zip_Code_Hash_15,Zip_Code_Hash_16,Zip_Code_Hash_17,Zip_Code_Hash_18,Zip_Code_Hash_19,Claim Injury Type Encoded,Accident_Season_Sin,Accident_Season_Cos
Claim Identifier,,,,,,,,,,,,,,,,,,,,,
5393875,2019-12-30,31.0,NaN,1988.0,0.0,27.0,10.0,62.0,1.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.000000e+00,1.000000e+00
5393091,2019-08-30,46.0,1745.93,1973.0,4.0,97.0,49.0,38.0,4.0,1,...,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,3,1.224647e-16,-1.000000e+00
5393889,2019-12-06,40.0,1434.80,1979.0,0.0,79.0,7.0,10.0,6.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,3,-1.000000e+00,-1.836970e-16
5393887,2019-12-30,61.0,NaN,1958.0,0.0,16.0,43.0,36.0,1.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.000000e+00,1.000000e+00
5393863,2019-12-26,67.0,NaN,1952.0,0.0,31.0,10.0,38.0,5.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.000000e+00,1.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6165265,2022-12-14,35.0,NaN,1987.0,0.0,45.0,10.0,42.0,4.0,1,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165285,2022-12-15,33.0,NaN,1989.0,0.0,74.0,37.0,35.0,6.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165506,2022-12-13,61.0,991.08,1961.0,1.0,98.0,80.0,34.0,3.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,3,-1.000000e+00,-1.836970e-16
6165339,2022-12-14,24.0,NaN,1998.0,0.0,59.0,59.0,55.0,5.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16
6165075,2022-12-13,72.0,NaN,1950.0,0.0,25.0,90.0,-9.0,3.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,-1.000000e+00,-1.836970e-16

In [ ]:
# Import dataset
test_df = pd.read_csv('./preprocessed_data/test_data.csv', index_col = 'Claim Identifier')
test_df

,Accident Date,Age at Injury,Average Weekly Wage,Birth Year,IME-4 Count,WCIO Cause of Injury Code,WCIO Nature of Injury Code,WCIO Part Of Body Code,Number of Dependents,Known Accident Date,...,Zip_Code_Hash_12,Zip_Code_Hash_13,Zip_Code_Hash_14,Zip_Code_Hash_15,Zip_Code_Hash_16,Zip_Code_Hash_17,Zip_Code_Hash_18,Zip_Code_Hash_19,Accident_Season_Sin,Accident_Season_Cos
Claim Identifier,,,,,,,,,,,,,,,,,,,,,
6165911,2022-12-24,19.0,NaN,2003.0,0.0,31.0,10.0,54.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166141,2022-11-20,19.0,NaN,2003.0,0.0,75.0,10.0,10.0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000e+00,-1.836970e-16
6165907,2022-12-26,59.0,NaN,1963.0,0.0,68.0,49.0,62.0,0,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166047,2022-12-28,55.0,NaN,1967.0,0.0,25.0,10.0,53.0,6,1,...,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6166102,2022-12-20,25.0,NaN,1997.0,0.0,79.0,40.0,37.0,5,1,...,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-1.000000e+00,-1.836970e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6553137,2012-09-12,52.0,NaN,1960.0,0.0,NaN,NaN,NaN,5,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.224647e-16,-1.000000e+00
6553119,2024-05-22,59.0,NaN,1965.0,0.0,NaN,NaN,NaN,1,1,...,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17
6553542,2024-05-06,45.0,NaN,1979.0,0.0,NaN,NaN,NaN,5,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17
6553455,2024-02-24,42.0,NaN,1981.0,0.0,NaN,NaN,NaN,5,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000e+00,1.000000e+00
6553594,2024-06-05,NaN,NaN,NaN,0.0,NaN,NaN,NaN,5,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000e+00,6.123234e-17

## <span style="color:salmon"> 2. Prepare Dataset </span>

Define y as a target "Claim Injury Type Encoded" and X with all the other columns

In [ ]:
X = df.drop(["Claim Injury Type Encoded"], axis = 1)
y = df["Claim Injury Type Encoded"]

Split the data and the target to X_train, X_test, y_train, y_test, where test_size should be equal to 0.25, stratify equal to target and shuffle equal to True

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size = 0.75, stratify = y, shuffle = True)

Define X_test

In [ ]:
X_test = test_df.copy()

Check missing values in each dataset:

In [ ]:
X_train.isna().sum().sort_values()[X_train.isna().sum() != 0]

Birth Year                      1649
Age at Injury                   1649
WCIO Cause of Injury Code      11680
WCIO Nature of Injury Code     11700
WCIO Part Of Body Code         12776
Average Weekly Wage           272969
dtype: int64

In [ ]:
X_val.isna().sum().sort_values()[X_val.isna().sum() != 0]

Birth Year                      537
Age at Injury                   537
WCIO Nature of Injury Code     3955
WCIO Cause of Injury Code      3958
WCIO Part Of Body Code         4304
Average Weekly Wage           91130
dtype: int64

In [ ]:
X_test.isna().sum().sort_values()[X_test.isna().sum() != 0]

Birth Year                       982
Age at Injury                    982
WCIO Part Of Body Code          9549
WCIO Cause of Injury Code      10348
WCIO Nature of Injury Code     10560
Average Weekly Wage           335753
dtype: int64

Input `Average Weekly Wage` and variables created from it

In [ ]:
median_avg_week_wage = X_train['Average Weekly Wage'].median()

X_train['Average Weekly Wage'] = X_train['Average Weekly Wage'].fillna(median_avg_week_wage)
X_val['Average Weekly Wage'] = X_val['Average Weekly Wage'].fillna(median_avg_week_wage)
X_test['Average Weekly Wage'] = X_test['Average Weekly Wage'].fillna(median_avg_week_wage)

In [ ]:
financial_impact(X_train)
financial_impact(X_val)
financial_impact(X_test)

*Input `Age at Injury` and variables that can be calculated with it*

In [ ]:
median_age_at_injury = X_train['Age at Injury'].median()

X_train['Age at Injury'] = X_train['Age at Injury'].fillna(median_age_at_injury)
X_val['Age at Injury'] = X_val['Age at Injury'].fillna(median_age_at_injury)
X_test['Age at Injury'] = X_test['Age at Injury'].fillna(median_age_at_injury)

In [ ]:
def calculate_birth_year(df):
    # Ensure the correct format of 'Birth Year'
    df['Accident Date'] = pd.to_datetime(df['Accident Date'], errors='coerce')

    # Filter the rows where 'Birth Year' is NaN, but 'Age at Injury' and 'Accident Date' are not NaN
    condition = df['Birth Year'].isna() & df['Age at Injury'].notna() & df['Accident Date'].notna()

    # Replace missing 'Birth Year' with the difference between 'Accident Date' year and 'Age at Injury'
    df.loc[condition, 'Birth Year'] = df.loc[condition, 'Accident Date'].dt.year - df.loc[condition, 'Age at Injury']

In [ ]:
calculate_birth_year(X_train)
calculate_birth_year(X_val)
calculate_birth_year(X_test)

Drop the columns: Accident Date

In [ ]:
X_train.drop('Accident Date', axis=1, inplace=True)
X_val.drop('Accident Date', axis=1, inplace=True)
X_test.drop('Accident Date', axis=1, inplace=True)

Scale the data:

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

## <span style="color:salmon"> 3. Neural Networking </span>

## <span style="color:yellow"> TESTAR ISTO </span>

NOTA: Hiperpar√¢metros Recomendados

- hidden_layer_sizes (Arquitetura da rede):
    - Redes profundas geralmente t√™m 2-4 camadas escondidas.
    - N√∫mero de neur√¥nios em cada camada deve ser ajustado com base na complexidade do dataset.
    - Sugest√£o inicial: testar configura√ß√µes como (64, 32), (128, 64, 32) ou (100, 50).
- activation (Fun√ß√£o de ativa√ß√£o):
    - Para dados complexos:
    - relu (ReLU): Melhor para grandes redes e tarefas gerais.
    - tanh: Pode ser √∫til para dados com distribui√ß√£o centrada em torno de 0.
    - Evite logistic (sigm√≥ide) em redes profundas, pois sofre com problemas de gradiente desaparecido.
- solver (Otimizador):
    - adam: R√°pido e eficiente para a maioria das situa√ß√µes.
    - lbfgs: Melhor para datasets pequenos ou quando o treinamento converge rapidamente.
    - sgd: √ötil se ajustar uma taxa de aprendizado manual.
- alpha (Regulariza√ß√£o L2):
    - Controla overfitting. Teste valores entre 0.0001 e 0.01.
    - Sugest√£o: [0.0001, 0.001, 0.01].
- max_iter (N√∫mero m√°ximo de itera√ß√µes):
    - Valores como 200-500 s√£o suficientes para a maioria dos datasets.
    - Ajuste se a rede n√£o convergir.

Applies MLP classifier:

In [ ]:
model_mlp = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=200, random_state=42).fit(X_train, y_train)

In [ ]:
y_train_pred = model_mlp.predict(X_train)

In [ ]:
y_val_pred = model_mlp.predict(X_val)

#### <span style="color:salmon"> 3.1  Evaluate the model </span>

In [ ]:
class_mapping = {
    0:'1. CANCELLED', 
    1:'2. NON-COMP',
    2:'3. MED ONLY', 
    3:'4. TEMPORARY',
    4:'5. PPD SCH LOSS', 
    5:'6. PPD NSL', 
    6:'7. PTD', 
    7:'8. DEATH'
}

# Use the values from class_mapping as the target names
target_names = list(class_mapping.values())

Compute confusion matrix to evaluate the accuracy of a classification

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_train_pred))
print("\nClassification Report:")
print(classification_report(y_train, y_train_pred, target_names=target_names))

In [ ]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred, target_names=target_names))

## <span style="color:salmon"> 4. Test Predictions </span>

Make validation predictions:

In [ ]:
y_test_pred = model_mlp.predict(X_test)

In [ ]:
test_id = test_df.index

In [ ]:
submission_df = pd.DataFrame({
    'Claim Identifier': test_id,
    'Claim Injury Type': y_test_pred
})